.Dd July 10, 2021
.Dt S7 3
.Sh NAME
.Nm S7
.Nd Iterators (C API)
.Sh SYNOPSIS
.In s7.h
.Ft s7_pointer
.Fn s7_make_iterator "s7_scheme *sc, s7_pointer e"
.Ft bool
.Fn s7_is_iterator "s7_pointer obj"
.Ft bool
.Fn s7_iterator_is_at_end "s7_scheme *sc, s7_pointer iter"
.Ft s7_pointer
.Fn s7_iterate "s7_scheme *sc, s7_pointer iter"
.Sh DESCRIPTION
These are the C equivalents of make-iterator, iterator?, iterator-at-end?, and iterate.
.Pp
.Sh EXAMPLES
.Bd -literal -offset indent
.Ed
.Pp
.Sh SEE ALSO
.Xr s7_iteration 3
.Sh AUTHORS
.An Bill Schottstaedt Aq Mt bil@ccrma.stanford.edu
.An Mike Scholz
provided the FreeBSD support (complex trig funcs, etc)
.An Rick Taube, Andrew Burnson, Donny Ward, and Greg Santucci
provided the MS Visual C++ support
.An Kjetil Matheussen
provided the mingw support
.An chai xiaoxiang
provided the msys2 support
