.Dd July 12, 2021
.Dt S7 3
.Sh NAME
.Nm S7
.Nd Characters
.Sh LIBRARY
libs7, -ls7
.Sh SYNOPSIS
.In s7.h
.Ft bool
.Fn s7_is_character "s7_pointer"
(char? p)
.Ft uint8_t
.Fn s7_character "s7_pointer p"
Scheme character -> unsigned C char
.Ft s7_pointer
.Fn s7_make_character "s7_scheme *sc, uint8_t c"
unsigned C char -> Scheme character
.Sh DESCRIPTION
.Sh EXAMPLES
.Bd -literal -offset indent
verbatim code here...
.Ed
.Pp
.Sh SEE ALSO
.Xr s7_datatypes 3 ,
.Xr s7_equality 3
.Pp
.Xr s7_booleans 3 ,
.Xr s7_lists 3 ,
.Xr s7_numbers 3 ,
.Xr s7_pairs 3 ,
.Xr s7_strings 3 ,
.Xr s7_vectors 3 ,
.Sh AUTHORS
.An Bill Schottstaedt Aq Mt bil@ccrma.stanford.edu
.An Mike Scholz
provided the FreeBSD support (complex trig funcs, etc)
.An Rick Taube, Andrew Burnson, Donny Ward, and Greg Santucci
provided the MS Visual C++ support
.An Kjetil Matheussen
provided the mingw support
.An chai xiaoxiang
provided the msys2 support
