.Dd July 10, 2021
.Dt S7 3
.Sh NAME
.Nm S7
.Nd History
.Sh LIBRARY
libs7, -ls7
.Sh SYNOPSIS
.In s7.h
.Ft s7_pointer
.Fn s7_stacktrace "s7_scheme *sc"
.Ft s7_pointer
.Fn s7_history "s7_scheme *sc"
the current (circular backwards) history buffer
.Ft s7_pointer
.Fn s7_add_to_history "s7_scheme *sc, s7_pointer entry"
add entry to the history buffer
.Ft bool
.Fn  s7_history_enabled "s7_scheme *sc"
.Ft bool
.Fn  s7_set_history_enabled "s7_scheme *sc, bool enabled"
.Sh DESCRIPTION
.Sh EXAMPLES
.Bd -literal -offset indent
verbatim code here...
.Ed
.Pp
.Sh SEE ALSO
.Xr s7_c_objects 3 ,
.Sh AUTHORS
.An Bill Schottstaedt Aq Mt bil@ccrma.stanford.edu
.An Mike Scholz
provided the FreeBSD support (complex trig funcs, etc)
.An Rick Taube, Andrew Burnson, Donny Ward, and Greg Santucci
provided the MS Visual C++ support
.An Kjetil Matheussen
provided the mingw support
.An chai xiaoxiang
provided the msys2 support
