.Dd July 10, 2021
.Dt S7 3
.Sh NAME
.Nm S7
.Nd Sequences
.Sh DESCRIPTION
See
.Pa https://ccrma.stanford.edu/software/snd/snd/s7.html#generalizedset
.Pp
"The somewhat non-standard generic sequence functions in s7 are:
.Pp
.Bd -literal -offset indent
(sort! sequence less?)
(reverse! sequence) and (reverse sequence)
(fill! sequence value (start 0) end)
(copy obj) and (copy source destination (start 0) end)
(object->string obj)
(object->let obj)
(length obj)
(append . sequences)
(map func . sequences) and (for-each func . sequences)
(equivalent? obj1 obj2)
.Ed
.Sh EXAMPLES
.Bd -literal -offset indent
.Ed
.Pp
.Sh SEE ALSO
.Xr s7_iterators 3
.Sh AUTHORS
.An Bill Schottstaedt Aq Mt bil@ccrma.stanford.edu
.An Mike Scholz
provided the FreeBSD support (complex trig funcs, etc)
.An Rick Taube, Andrew Burnson, Donny Ward, and Greg Santucci
provided the MS Visual C++ support
.An Kjetil Matheussen
provided the mingw support
.An chai xiaoxiang
provided the msys2 support
